from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path

import psycopg

from retail_import_common import (
    DEFAULT_ORDERS_TARGET_ROWS,
    build_table_defs,
    download_dataset,
    guess_column_type_sql,
    is_orders_table,
    load_env_file,
    normalize_column_name,
    normalize_table_name,
)


def pg_ident(name: str) -> str:
    safe = normalize_table_name(name)
    safe = safe.replace('"', '""')
    return f'"{safe}"'


def pg_col_ident(name: str) -> str:
    safe = normalize_column_name(name)
    safe = safe.replace('"', '""')
    return f'"{safe}"'


def create_table_postgres(conn: psycopg.Connection, table_def) -> None:
    table = pg_ident(table_def.name)
    pk = normalize_column_name(table_def.primary_key)

    column_defs: list[str] = []
    for col in table_def.columns:
        col_n = normalize_column_name(col)
        col_type = guess_column_type_sql(col_n)
        if col_n == pk and pk != "__row_id":
            column_defs.append(
                f"{pg_col_ident(col_n)} {col_type} GENERATED BY DEFAULT AS IDENTITY"
            )
        else:
            column_defs.append(f"{pg_col_ident(col_n)} {col_type}")

    if pk == "__row_id":
        column_defs.insert(0, '"__row_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
        pk_clause = ""
    else:
        pk_clause = f", PRIMARY KEY ({pg_col_ident(pk)})"

    ddl = f"CREATE TABLE IF NOT EXISTS {table} (" + ", ".join(column_defs) + pk_clause + ");"

    with conn.cursor() as cur:
        cur.execute(ddl)


def add_foreign_keys_postgres(conn: psycopg.Connection, table_def) -> None:
    if not table_def.foreign_keys:
        return

    table = pg_ident(table_def.name)
    with conn.cursor() as cur:
        for i, fk in enumerate(table_def.foreign_keys, start=1):
            sp = f"sp_{normalize_table_name(table_def.name)}_{i}"
            cur.execute(f"SAVEPOINT {pg_ident(sp)};")
            try:
                cur.execute(
                    f"""
                    ALTER TABLE {table}
                    ADD CONSTRAINT {pg_ident(fk.name)}
                    FOREIGN KEY ({pg_col_ident(fk.column)})
                    REFERENCES {pg_ident(fk.ref_table)} ({pg_col_ident(fk.ref_column)});
                    """.strip()
                )
                cur.execute(f"RELEASE SAVEPOINT {pg_ident(sp)};")
            except Exception:
                cur.execute(f"ROLLBACK TO SAVEPOINT {pg_ident(sp)};")
                cur.execute(f"RELEASE SAVEPOINT {pg_ident(sp)};")
                continue


def copy_csv_postgres(conn: psycopg.Connection, table_def, batch_bytes: int = 4 * 1024 * 1024) -> None:
    table = pg_ident(table_def.name)
    pk = normalize_column_name(table_def.primary_key)

    copy_columns = [normalize_column_name(c) for c in table_def.columns]
    if pk == "__row_id":
        copy_columns = [c for c in copy_columns if c != "__row_id"]

    cols_sql = ", ".join(pg_col_ident(c) for c in copy_columns)

    copy_sql = f"""
        COPY {table} ({cols_sql})
        FROM STDIN
        WITH (FORMAT csv, HEADER true, NULL '', QUOTE '"', ESCAPE '"')
    """.strip()

    file_size = None
    try:
        file_size = int(Path(table_def.csv_path).stat().st_size)
    except Exception:
        file_size = None

    log_every = int(os.getenv("PG_COPY_LOG_EVERY_BYTES", str(64 * 1024 * 1024)))
    if log_every <= 0:
        log_every = 64 * 1024 * 1024

    bytes_written = 0
    next_log_at = log_every

    with conn.cursor() as cur:
        with cur.copy(copy_sql) as copy:
            with open(table_def.csv_path, "rb") as f:
                while True:
                    chunk = f.read(batch_bytes)
                    if not chunk:
                        break
                    copy.write(chunk)
                    bytes_written += len(chunk)

                    if bytes_written >= next_log_at:
                        if file_size:
                            pct = (bytes_written / file_size) * 100.0
                            print(
                                f"  - {table_def.name}: {bytes_written/1024/1024:.1f} MiB/{file_size/1024/1024:.1f} MiB ({pct:.1f}%)",
                                flush=True,
                            )
                        else:
                            print(
                                f"  - {table_def.name}: {bytes_written/1024/1024:.1f} MiB written",
                                flush=True,
                            )
                        next_log_at += log_every


def ensure_orders_size_postgres(conn: psycopg.Connection, orders_pk: str, target_rows: int) -> None:
    pk = normalize_column_name(orders_pk)
    with conn.cursor() as cur:
        cur.execute('SELECT COUNT(*) FROM "orders";')
        current = int(cur.fetchone()[0])

    if current >= target_rows:
        return

    if pk != "__row_id":
        with conn.cursor() as cur:
            cur.execute("SELECT pg_get_serial_sequence(%s, %s);", ("orders", pk))
            seq = cur.fetchone()[0]
            if seq:
                cur.execute(
                    f"SELECT setval(%s, (SELECT COALESCE(MAX({pg_col_ident(pk)}), 0) FROM \"orders\"), true);",
                    (seq,),
                )
        conn.commit()

    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'orders'
            ORDER BY ordinal_position;
            """
        )
        cols = [r[0] for r in cur.fetchall() if r[0] != pk]

    cols_sql = ", ".join(pg_col_ident(c) for c in cols)

    print(
        f"  - orders currently {current:,}, target {target_rows:,}",
        flush=True,
    )

    while current < target_rows:
        to_add = min(target_rows - current, max(current, 1))
        t0 = time.perf_counter()
        with conn.cursor() as cur:
            cur.execute(
                f"INSERT INTO \"orders\" ({cols_sql}) SELECT {cols_sql} FROM \"orders\" LIMIT %s;",
                (to_add,),
            )
            inserted = cur.rowcount if cur.rowcount is not None else to_add
        conn.commit()
        current += inserted

        print(
            f"  - orders expanded: +{inserted:,} -> {current:,}/{target_rows:,} ({time.perf_counter() - t0:.2f}s)",
            flush=True,
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Import the Kaggle Retail Data Warehouse dataset into PostgreSQL."
    )
    parser.add_argument(
        "--dataset-id",
        default=os.getenv("KAGGLE_DATASET_ID", None) or None,
        help="Kaggle dataset id (default: retail DWH 12-table dataset).",
    )
    parser.add_argument(
        "--reset",
        action="store_true",
        help="Drop and recreate tables before import.",
    )
    parser.add_argument(
        "--orders-target-rows",
        type=int,
        default=int(os.getenv("ORDERS_TARGET_ROWS", str(DEFAULT_ORDERS_TARGET_ROWS))),
        help=f"Target number of rows in orders table (default: {DEFAULT_ORDERS_TARGET_ROWS}).",
    )
    return parser.parse_args()


def main() -> int:
    load_env_file(Path(".env"))
    args = parse_args()

    dataset_id = args.dataset_id or os.getenv("KAGGLE_DATASET_ID")
    print("Downloading dataset via kagglehub...", flush=True)
    dataset_path = download_dataset(dataset_id) if dataset_id else download_dataset()
    print(f"Dataset ready at: {dataset_path}", flush=True)

    print("Discovering CSV tables...", flush=True)
    table_defs = build_table_defs(dataset_path)
    print(f"Discovered {len(table_defs)} tables.", flush=True)

    conn = psycopg.connect(
        host=os.getenv("POSTGRES_HOST", "localhost"),
        port=int(os.getenv("POSTGRES_PORT", "5432")),
        dbname=os.getenv("POSTGRES_DB", "benchmark_db"),
        user=os.getenv("POSTGRES_USER", "benchmark_user"),
        password=os.getenv("POSTGRES_PASSWORD", "benchmark_pass"),
    )

    try:
        conn.autocommit = False

        if args.reset:
            print("Reset enabled: dropping existing tables...", flush=True)
            with conn.cursor() as cur:
                for td in reversed(table_defs):
                    cur.execute(f"DROP TABLE IF EXISTS {pg_ident(td.name)} CASCADE;")
            conn.commit()

        for td in table_defs:
            create_table_postgres(conn, td)
        conn.commit()

        for td in table_defs:
            start = time.perf_counter()
            print(f"Copying {td.name}...", flush=True)
            copy_csv_postgres(conn, td)
            conn.commit()
            print(
                f"[OK] Copied {td.name} in {time.perf_counter() - start:.2f}s",
                flush=True,
            )

        for td in table_defs:
            add_foreign_keys_postgres(conn, td)
        conn.commit()

        orders_def = next((d for d in table_defs if is_orders_table(d.name)), None)
        if orders_def:
            print(
                f"Expanding orders to {args.orders_target_rows:,} rows (database-side duplication)...",
                flush=True,
            )
            start = time.perf_counter()
            ensure_orders_size_postgres(conn, orders_def.primary_key, args.orders_target_rows)
            print(
                f"[OK] Orders expanded in {time.perf_counter() - start:.2f}s",
                flush=True,
            )

    finally:
        conn.close()

    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
